### ISSUE TITLE
Building develop branch leads to incomplete type error

### ISSUE THREAD

**Issue by schoonhovenrichard** [jwbuurlage/slicevis#11]
I am trying to build the develop branch of Recast to work with the develop branch with SliceRecon. This is done because spawning a SliceRecon server crashes Recast if I use the develop branch of SR and the master branch of Recast (this will be a different issue perhaps).

The installation procedure I tried is based on the install script provided in conda/build.sh (I also tried cloning the repo and running cmake but this lead to all sorts of problems solved in the conda build script):

1) In order to use the work done before by using the meta.yaml file provided in conda/meta.yaml we created a conda debug environment:
```conda debug conda/``` followed by:
```cd /export/scratch1/schoonho/anaconda3/conda-bld/debug_1571407408363/work && source /export/scratch1/schoonho/anaconda3/conda-bld/debug_1571407408363/work/build_env_setup.sh```
2) We prepare glmConfig.cmake:
```mkdir ext/glm/build && cd ext/glm/build```
```cmake ..```
```cd ../../../```
3) As instructed in the build script, we run:
```declare -a CMAKE_PLATFORM_FLAGS```
```CMAKE_PLATFORM_FLAGS=(-DCMAKE_TOOLCHAIN_FILE="${RECIPE_DIR}/cross-linux.cmake")```

4) We create the build folder and run cmake with the provided flags in ```build.sh```:
```mkdir build && cd build```
Followed by:
```
cmake ..                                        \
      -DCMAKE_INSTALL_PREFIX=$PREFIX            \
      -DCMAKE_INSTALL_LIBDIR=$PREFIX/lib        \
      -DCMAKE_BUILD_TYPE=Release                \
      ${CMAKE_PLATFORM_FLAGS[@]}                \
      -DOpenGL_GL_PREFERENCE="LEGACY"           \
      -DGLFW_BUILD_EXAMPLES=OFF                 \
      -DGLFW_BUILD_TESTS=OFF                    \
      -DGLFW_BUILD_DOCS=OFF                     \
      -Dglm_DIR="ext/glm/build"
```
5) We run the make command ```make -j8```.

I get the following errors:
```
.../ext/tomopackets/tomop/module.cpp:68:52: error: use of 'types' before deduction of 'auto'
         using Init = typename decltype(hana::unpack(
                                        ~~~~~~~~~~~~^
             types, hana::template_<py::detail::initimpl::constructor>))::type;
```

```
.../ext/tomopackets/tomop/module.cpp:77:20: error: unable to deduce lambda return type from 'pack'
             return pack;
```

```
.../ext/tomopackets/tomop/module.cpp:81:14: error: 'void pack' has incomplete type
         auto pack = hana::unpack(names, indirection);
```

The GCC version that was used was 9.1.1. 

I also tried running:

```CXX=... CC=... make -j 8```

For GCC version 8.3.0 this gave a different error I did not fully understand:

```
CMakeFiles/test_server.dir/test/test_server.cpp.o: undefined reference to symbol '_ZSt20__throw_length_errorPKc@@GLIBCXX_3.4'
/bin/ld: /export/scratch1/schoonho/anaconda3/conda-bld/debug_1571407408363/_h_env/lib/libstdc++.so.6: error adding symbols: DSO missing from command line
```
For GCC version 7.3.0 this gave the same errors as 9.1.1. I am not entirely sure what happened when I ran with gcc 8.3.0. 

Also, I see that I have Boost version 1.67.0 if that is relevant since the errors seem Hana related.

Any ideas what I might try?

**Comment by jwbuurlage** [comment]
> This is done because spawning a SliceRecon server crashes Recast if I use the develop branch of SR and the master branch of Recast (this will be a different issue perhaps).

RECAST3D and SliceRecon use TomoPackets as their communication mechanism. If there is a (major) version mismatch between the TomoPackets that they were build with, the contents of the packets can be different then what they expect when deserializing. When the software reaches 1.0, it makes sense to do a handshake on the TomoPackets version when creating a new scene, and to gracefully return an error if there is a mismatch. As TomoPackets was still undergoing frequent changes, the developer has to make sure to use the same version for all components. In other words, that mismatching versions crash is known and expected for now, and is in my opinion not a problem.

> Any ideas what I might try?

I have updated all the `develop` branches, and merged in the changes by the rest of the team that were pulled into `master` over the last weeks into the `develop` branches. 

As you can see the error(s) that you are seeing is not in RECAST, but in TomoPackets. I do not know what changed, but somehow type deduction fails in the generation of the Python bindings.

For me the (updated) `develop` branch of TomoPackets builds fine with Clang 7 and Boost 1.67, but any (more) recent version should work. 

For now, try once more with GCC 9.x, and else try with Clang instead of GCC. I will look into why this failed on GCC in the future.

For development, I would recommend running the develop branch of all three components (TomoPackets, SliceRecon, RECAST3D), and keeping them up to date.

**Comment by schoonhovenrichard** [comment]
It works now with GCC 9.1.1! I re-cloned everything and repeated the aforementioned steps (with the addition of running ```git submodule update --init --recursive``` and it builds. Thanks for your help!
