### ISSUE TITLE
Conda package needs cleaning up

### ISSUE THREAD

**Issue by wjp** [jwbuurlage/slicevis#13]
The conda package has a number of files in it that it shouldn't, such as assimp/glfw3 development files. In particular the glfw3 cmake files that contain paths from the build environment cause problems.

```
$ tar tf recast3d-1.0.0.rc.1-hf484d3e_1.tar.bz2
info/hash_input.json
info/has_prefix
info/index.json
info/files
info/about.json
info/git
info/paths.json
info/recipe/meta.yaml.template
info/recipe/cross-linux.cmake~
include/assimp/vector2.inl
include/assimp/color4.inl
include/assimp/quaternion.inl
include/assimp/vector3.inl
include/assimp/matrix3x3.inl
include/assimp/material.inl
include/assimp/matrix4x4.inl
lib/libglfw3.a
lib/static/libimgui.a
lib/libassimp.a
info/recipe/build_environment.yml~
include/assimp/NullLogger.hpp
include/assimp/LogStream.hpp
include/assimp/IOStream.hpp
include/assimp/ProgressHandler.hpp
include/assimp/DefaultLogger.hpp
include/assimp/Logger.hpp
include/assimp/IOSystem.hpp
include/assimp/Exporter.hpp
include/assimp/Importer.hpp
info/recipe/meta.yaml~
info/recipe/build.sh~
info/test/run_test.sh
info/recipe/build.sh
bin/assimp
bin/recast3d
info/recipe/conda_build_config.yaml
info/recipe/meta.yaml
lib/pkgconfig/glfw3.pc
lib/pkgconfig/assimp.pc
lib/cmake/glfw3/glfw3Config.cmake
info/recipe/cross-linux.cmake
lib/cmake/glfw3/glfw3Targets-release.cmake
lib/cmake/glfw3/glfw3ConfigVersion.cmake
lib/cmake/assimp-4.0/assimp-config-version.cmake
lib/cmake/assimp-4.0/assimp-config.cmake
lib/cmake/glfw3/glfw3Targets.cmake
include/assimp/Compiler/poppack1.h
include/assimp/Compiler/pushpack1.h
include/assimp/ai_assert.h
include/assimp/vector2.h
include/assimp/color4.h
include/assimp/DefaultIOSystem.h
include/assimp/version.h
include/assimp/quaternion.h
include/assimp/vector3.h
include/assimp/cfileio.h
include/assimp/DefaultIOStream.h
include/assimp/importerdesc.h
include/assimp/matrix3x3.h
include/assimp/camera.h
include/assimp/texture.h
include/assimp/light.h
include/assimp/metadata.h
include/assimp/defs.h
include/assimp/matrix4x4.h
include/assimp/cexport.h
include/assimp/scene.h
include/assimp/SceneCombiner.h
include/assimp/types.h
include/GLFW/glfw3native.h
include/assimp/anim.h
include/assimp/cimport.h
include/assimp/mesh.h
include/assimp/postprocess.h
include/assimp/Compiler/pstdint.h
include/assimp/config.h
include/assimp/material.h
include/GLFW/glfw3.h
```

**Comment by jwbuurlage** [comment]
Pinging @ahendriksen who set up the Conda package if he'd like to take a look at this?

**Comment by ahendriksen** [comment]
The `make install` in `build.sh` (see [here](https://github.com/cicwi/RECAST3D/blob/8744e7383ff4acc662a71186f6ab6c201ceee6c7/conda/build.sh#L32)) installs glfw and assimp because they are built as part of the RECAST3D build. 

We are not the [first](http://cmake.3232098.n2.nabble.com/Disabling-INSTALL-target-for-subdirectory-td7595059.html) to have this problem. The solution proposed there is to add `EXCLUDE_FROM_ALL` to all `add_subdirectory` calls.

I think that replacing `add_subdirectory(...  )` by  `add_subdirectory(...  EXCLUDE_FROM_ALL)` could fix the issue
[here](https://github.com/cicwi/RECAST3D/blob/8744e7383ff4acc662a71186f6ab6c201ceee6c7/CMakeLists.txt#L29),
 [here](https://github.com/cicwi/RECAST3D/blob/8744e7383ff4acc662a71186f6ab6c201ceee6c7/CMakeLists.txt#L79),
[here](https://github.com/cicwi/RECAST3D/blob/8744e7383ff4acc662a71186f6ab6c201ceee6c7/CMakeLists.txt#L103),
[here](https://github.com/cicwi/RECAST3D/blob/8744e7383ff4acc662a71186f6ab6c201ceee6c7/CMakeLists.txt#L125), and
[here](https://github.com/cicwi/RECAST3D/blob/8744e7383ff4acc662a71186f6ab6c201ceee6c7/CMakeLists.txt#L147).

I am not able to fix this in the coming two weeks.
