### ISSUE TITLE
Center of Rotation

### ISSUE THREAD

**Issue by aboulhaa** [jwbuurlage/slicevis#15]
Hello,

We have tested RECAST3D, managed to install and run successfully. But we have problem with the Center of Rotation. 
The visualization is blurred since the center of the rotation need to be adjusted to the one of the captured images.

I would like to ask if this is already implemented in RECAST3D.
If so, how can we adjust it? or is it explained somewhere in the manual?

Thank you.
Best regards,
Amal

**Comment by jwbuurlage** [comment]
Hi Amal,

You can fix center-of-rotation issues in one of two ways:

1. (Probably prefered). Modify the acquisition geometry, by using e.g. `tomop.parallel_vec_geometry_packet` instead of `tomop.parallel_beam_geometry_packet` for parallel beam. You can view the arguments to this packet using Python's `help(..)` functionality. The arguments follow the [ASTRA toolbox conventions](http://www.astra-toolbox.com/docs/geom3d.html). With a vector geometry, you should in principle be able to fix all consistent alignment issues you can encounter.

2. For parallel beam, if your center of rotation correction can be modelled by an in-plane rotation/translation, you can try [using the `--tilt` option](https://github.com/cicwi/RECAST3D/blob/e387abe731ccd3b1cd1db6c6a734017fe10697ca/slicerecon/src/slicerecon_server.cpp#L38) of `slicerecon_server`. This will show two inputs fields in the RECAST3D GUI, corresponding to an in-plane translation (in pixels), and rotation (in degrees) for all the projection images.

**Comment by aboulhaa** [comment]
Hello Jan,

thank you for your reply.

I tried the tilt option but noticed no change in the GUI:
slicerecon_server --slice-size 512 --tilt

Should I seek these values in a particular tab?
Or make some change in the usage - maybe add the numbers in the command line?

**Comment by jwbuurlage** [comment]
They should be in a collapsing header tab called 'parameters'. 

  `slicerecon_server --slice-size 512 --tilt`

This command is correct. Do note though that it is only implemented for `parallel_beam` geometries. Otherwise, you can go with option 1 and modify the geometry vectors directly.

**Comment by jwbuurlage** [comment]
Let me know if you need any additional help!
